version: '3.8'

services:
  app:
    build: .
    container_name: grababargain-api
    depends_on:
      - postgres
    profiles:
      - prod
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/DBforDevops
      SPRING_DATASOURCE_USERNAME: grababargain
      SPRING_DATASOURCE_PASSWORD: engsoftware@2024
      SPRING_PROFILES_ACTIVE: prod

  postgres:
    image: postgres:16
    container_name: grababargain-database
    restart: always
    environment:
      POSTGRES_DB: DBforDevops
      POSTGRES_USER: grababargain
      POSTGRES_PASSWORD: engsoftware@2024
      TZ: America/Araguaina
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local