version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: grababargain-database
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: America/Araguaina
    volumes:
      - db:/var/lib/postgresql/data
    profiles:
      - prod
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    ports:
      - "5432:5432"
  app:
    build: .
    image: jlpimenta11/spring
    container_name: grababargain-api
    depends_on:
      - postgres
    links:
      - postgres
    profiles:
      - prod
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
networks:
  app-network:
    driver: bridge
volumes:
  db: