CREATE TABLE product
(
    iden_product BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(50)                             NOT NULL,
    desc_product VARCHAR(150),
    price        DECIMAL,
    CONSTRAINT pk_product PRIMARY KEY (iden_product)
);