CREATE TABLE "order"
(
    iden_order    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_date    TIMESTAMP WITHOUT TIME ZONE,
    status        VARCHAR(255),
    iden_customer BIGINT                                  NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (iden_order)
);

ALTER TABLE "order"
    ADD CONSTRAINT ORDER_FK_01 FOREIGN KEY (iden_customer) REFERENCES customer (iden_customer);